### ISSUE TITLE
Proxy Server Configuration

### ISSUE THREAD

**Issue by dnwk** [ExLibrisGroup/primo-explore-devenv#1]
"Edit the proxy server under /gulp/config.js: var PROXY_SERVER = http://your-server:your-port". I don't quite understand this instruction. What kind of Proxy server we need to put in? Is it our Primo URL?

**Comment by noamamit92** [comment]
Indeed, I will added an explanation:

Edit the proxy server (Your Primo Front-End Url) under /gulp/config.js: `var PROXY_SERVER = http://your-server:your-port`,

**Comment by noamamit92** [comment]
closed by https://github.com/ExLibrisGroup/primo-explore-devenv/commit/56d78fdff0c64a3824a6822fe133df2462c17ebd

**Comment by dnwk** [comment]
We are hosted Primo.  If I put in https://alliance-primo-sb.hosted.exlibrisgroup.com:443, it will give an error message "cannot GET".  If I put in http://alliance-primo-sb.hosted.exlibrisgroup.com:80,  it will stay in constant loading without timeout and without loading anything.

**Comment by noamamit92** [comment]
Hi,

Not sure what is the reason, but this works:

var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com:80';


it did load for me,


you can try working in incognito mode

or waiting a little longer


Also make sure that you restart your server (gulp run --view ...)

after changing the PROXY_SERVER definition



Please update me if it works


Thanks


2016-08-08 20:05 GMT+03:00 Delroy L. <notifications@github.com>:

**Comment by dnwk** [comment]
Do I need to put my IP address in as allow for X Webservice?  I thought previously using those Primo Search API, I need to get my IP address white listed.

**Comment by dnwk** [comment]
For whatever reason, it still get "cannot GET / " error using that configuration as proxy server. Does it because there are some firewall that only allow certain IP addresses?

**Comment by noamamit92** [comment]
No need for that,

What is the url you are opening in the browser?

**Comment by dnwk** [comment]
localhost:8003

**Comment by noamamit92** [comment]
Needs to be:



   -

   Open a browser and type in the following url:

   localhost:8003/primo-explore/?vid=your-view-code

   example: http://localhost:8003/primo-explore/search?vid=Auto1

**Comment by dnwk** [comment]
It worked. Thanks

**Comment by dnwk** [comment]
I have one additional question. Does edit color.json has any effect?
Thanks

**Comment by noamamit92** [comment]
See in:
https://github.com/ExLibrisGroup/primo-explore-package/blob/master/VIEW_CODE/css/README.md

The section
Css Recipe 1 - Color Scheme (Starting from August 2016 Release
