### ISSUE TITLE
chore(update npm/node): Update recommended software versions and dependencies

### ISSUE THREAD

**Issue by atla5** [ExLibrisGroup/primo-explore-devenv#105]
### Background
- the versions of node and npm specified in the [README](https://github.com/ExLibrisGroup/primo-explore-devenv/blob/1.0.3/README.md) (#12) are `v6.9.2` and `3.3.12` respectively
- the `@latest` versions of those are `v12.4.0` and `6.9.2`, respectively (!!), and neither are being [supported](https://en.wikipedia.org/wiki/Long-term_support) anymore 
- an `npm audit` turns up 74 vulnerabilities, 60 of which can likely be solved by running `npm audit fix`
- it looks like [PR #103](/ExLibrisGroup/primo-explore-devenv/pull/103) addresses these concerns

### Desired Changes
- ensure that the devenv works on at least node version `10.16.0` ([LTS EOL 2021](https://nodejs.org/en/about/releases/)) and npm version `6.X` ([npm LTS policy](https://blog.npmjs.org/post/162451604515/the-npm-clis-long-term-support-lts-policy)) 
- run `$npm audit fix` and run tests to ensure there aren't any regressions
- update the README to reference the (earliest and) most recent versions of `npm` and `node` the devenv supports

**Comment by atla5** [comment]
note, related: #103 #12

**Comment by etgrieco** [comment]
@atla5 Thank you!

**Comment by noamamit92** [comment]
closing as PR are merged
