### ISSUE TITLE
Instruction and command line

### ISSUE THREAD

**Issue by yurj** [ExLibrisGroup/primo-explore-devenv#108]
Please add "run in commandline as Administrator" for npm install npm@3.3.12 -g

**Comment by yurj** [comment]
Also please add instructions on how to install if a user is not an administrator.

**Comment by yurj** [comment]
The instructions  in https://github.com/ExLibrisGroup/primo-explore-devenv does not work. Can you review/update them for a non Administrator user?

**Comment by noamamit92** [comment]
done by adding:

Note: If you are not the Administrator of your machine, you might get into problems in the flow below, we recommend using the "Node.js command prompt (search for cmd in your pc to locate it) whenever the instructions below refer to "command line".
