### ISSUE TITLE
main.js: no angular or app variables?

### ISSUE THREAD

**Issue by allanberry** [ExLibrisGroup/primo-explore-devenv#110]
I'm experimenting with the `--browserify` option in Primo VE, and trying to get the basic Hello World running from [this tutorial](https://github.com/ExLibrisGroup/primo-explore-package/tree/master/VIEW_CODE/js), using `main.js`:

```JavaScript
app.component('myInstitutionComponent', {
    template: `<span style="margin-left: 40%;">Hello World</span>`
});
```

However, I'm getting the `Uncaught ReferenceError: app is not defined` error in my console (which makes sense, of course).

So is `app`, or maybe `angular`, meant to be imported from a module somewhere?

I understand that [--browserify is pretty unsupported](https://github.com/ExLibrisGroup/primo-explore-devenv/issues/43).  But I would _really_ like it to work, so I can use ES2015, npm modules, etc.  I would be a big fan.

Thanks!

**Comment by noamamit92** [comment]
Hi @allanberry - do you have the following declared in your code?
 var app = angular.module('viewCustom', ['angularLoad']);

**Comment by allanberry** [comment]
Thanks @noamamit92, that's what I needed.  Much obliged, it works now.

Is that documented anywhere?  I wonder what other elementary things I don't know.  :)
