### ISSUE TITLE
Documentation: Update PROXY_SERVER variable instructions in README.md

### ISSUE THREAD

**Issue by cudevmaxwell** [ExLibrisGroup/primo-explore-devenv#111]
In `README.md`, under `Installation`, at step 9: 

9.  Edit Gulp configuration file's <i>proxy server</i> setting, found at <b>gulp/config.js</b> : `var PROXY_SERVER = http://your-server:your-port` (Make sure to use your real Sandbox or Production Primo Front-End URL.) Note that for SSL environments (HTTPS) define the server as: `var PROXY_SERVER = https://your-server:443`

I think this should be changed to:

9.  Edit Gulp configuration file's <i>proxy server</i> setting, found at <b>gulp/config.js</b> : `var PROXY_SERVER = https://your-server` (Make sure to use your real Sandbox or Production Primo Front-End URL.)`

The current instructions don't work, they cause this error:

```
Error: connect ETIMEDOUT IP:PORT
at Object.exports._errnoException (util.js:1022:11)
at exports._exceptionWithHostPort (util.js:1045:20) 
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

**Comment by noamamit92** [comment]
@cudevmaxwell  can you share the proxy definition that did not work for you and your complete fe url including the vid?

**Comment by cudevmaxwell** [comment]
Sure. 

`var PROXY_SERVER = https://ocul-crl.primo.exlibrisgroup.com:443` 

and https://ocul-crl.primo.exlibrisgroup.com/discovery/search?vid=01OCUL_CRL:CRL_DEFAULT

**Comment by noamamit92** [comment]
I used this definition:

var PROXY_SERVER = 'https://ocul-crl.primo.exlibrisgroup.com:443';


and it worked well .

Since generally, this has been working fine for other institutions and I feel its safer as defined in the documentation right now I dont want to change it unless we get additional feedback.

**Comment by cudevmaxwell** [comment]
Alright, closing for now. Thanks for looking into it @noamamit92.
