### ISSUE TITLE
node version 6.9.2 dangerously outdated

### ISSUE THREAD

**Issue by gabriele-h** [ExLibrisGroup/primo-explore-devenv#114]
Node versions 6.x.x had End of life on 2019-04-30, see https://github.com/nodejs/Release/commit/c7be2c8908acd876a4393ff90c62100942ebba1b#diff-04c6e90faac2675aa89e2176d2eec7d8

I had to do quite some digging to even find that date, as the currently active version of node is 10.

Are there any plans to update primo-explore-devenv to current versions or is this GitHub project actually dead?

Also: Recommending in the README of the project to install node globally is not just in sight of the **very** outdated version an issue.

**Comment by gabriele-h** [comment]
I realize this is the duplicate of various other issues on the topic. But @noamamit92 are there any plans to update this repository at all? It hasn't seen much attention from Ex Libris as far as I can see since 2018.

**Comment by noamamit92** [comment]
@gabriele-h  - We will update this repository

**Comment by noamamit92** [comment]
merged the relevant PR
