### ISSUE TITLE
gulp app-css --view MyView issue?

### ISSUE THREAD

**Issue by paulweimq** [ExLibrisGroup/primo-explore-devenv#118]
Hi Noam

After pulling the latest primo-explore-devenv package, when we attempt to run the following command:
gulp app-css --view MyView

we get the following 'Error:CssSyntaxError in plugin "gulp-autoprefixer"'.
This seems to pertain to:
    C:\Code\primo-explore-devenv\www\styles\main.css:9351:24: Unknown word  9349 |           position: absolute;

  9350 |           float: left;
> 9351 |           margin-right margin-left: 0.25em;
       |                        ^

 
More detailed output below...
Anyone encountered this or know how to fix it?

[13:59:20] Using gulpfile C:\Code\primo-explore-devenv\gulpfile.js
[13:59:20] Starting 'app-css'...
[13:59:20] Starting 'extract-scss-files'...
https://multisearch.mq.edu.au:443/primo-explore/lib/scsss.tar.gz
[13:59:21] Finished 'extract-scss-files' after 904 ms
[13:59:21] Starting 'color-variables'...
[13:59:21] Finished 'color-variables' after 17 ms
[13:59:21] Starting 'compile-scss'...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.
  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist

Error:CssSyntaxError in plugin "gulp-autoprefixer"

Message:

    C:\Code\primo-explore-devenv\www\styles\main.css:9351:24: Unknown word  9349 |           position: absolute;

  9350 |           float: left;

> 9351 |           margin-right margin-left: 0.25em;

       |                        ^

  9352 |           left: -1.5em; }

  9353 |           [dir=rtl] prm-search-bar .advanced-search-wrapper .search-string .string-block prm-icon, [dir=rtl] prm-atoz-search-bar .advanced-search-wrapper .search-string .string-block prm-icon, [dir=rtl] prm-browse-search-bar .advanced-search-wrapper .search-string .string-block prm-icon, [dir=rtl] prm-tags-search-bar .advanced-search-wrapper .search-string .string-block prm-icon, [dir=rtl] prm-newspapers-search-bar .advanced-search-wrapper .search-string .string-block prm-icon {

Details:

    reason: Unknown word

    file: C:\Code\primo-explore-devenv\www\styles\main.css

    source: @charset "UTF-8";

.pseudo-full-cover, .absolute-full-cover {

  position: absolute;

  top: 0;

  left: 0;

  width: 100%;

  height: 100%; }

 

.pseudo-full-cover {

  content: ""; }

[snipped]

**Comment by noamamit92** [comment]
@paulweimq , Thanks .

We have noticed this too.

It is an old css bug in the application css which is fixed in the application in November and upgrading one of the third parties made is less forgiving for these bugs.

In the meantime , if you need to compile css or use any other critical functionality, I always recommend pulling the latest tag which holds the stable release (July 2020 release)
