### ISSUE TITLE
Clarify node and npm compatibility in readme and package.json

### ISSUE THREAD

**Issue by danmichaelo** [ExLibrisGroup/primo-explore-devenv#12]
Hi, the readme recommends installing very specific versions of node and npm globally. Since many users might already have a newer version of node installed (and might not use nvm), I wonder if there are there any known compability issues with newer versions of node and npm? If not, I suggest to rather recommend _minimum_ versions.

Also, any node and/or npm requirements should be made machine readable by also adding them to `package.json` using the [engines](https://docs.npmjs.com/files/package.json#engines) keyword. Esp. the minimum version of node needed.

**Comment by noamamit92** [comment]
@david-gang  - Assigned to you to review

**Comment by david-gang** [comment]
Hi @danmichaelo and @noamamit92 ,
Our aim is that the environment should work with the 4.x line which is currently the LTS. 
It was tested on the specific nodejs version 4.2.x.
There is no reason why it should not work with a later version which is smaller than nodejs 7.
I use nodejs 6.7 and it works nice. From nodejs 7 it will make problems with gulp 3.91
My suggestion is that we will target the 4.x and 6.x line which are the lts versions and add it as the engines keyword.

Thanks

**Comment by danmichaelo** [comment]
Thanks! Something like `"node" : ">=4.2 <7.0"`, then? That would be nice. 

Also I suggest in the README to change "Download and install nodejs version 4.2.x" to "Download and install the latest LTS version of Node from:", so people don't go hunting for the older 4.2.
