### ISSUE TITLE
app-css task problem because of bug in scsss.tar.gz

### ISSUE THREAD

**Issue by uleodolter** [ExLibrisGroup/primo-explore-devenv#120]
Hi @noamamit92,

Recently i discovered a bug in scsss.tar.gz, which is fetched from server when running the app-css task.  I opened a SF Case 00872718 which does contain a fix, not 100% sure if this was intended.  I replaced `rtl` by `rtl-prop` and inserted a comma between `margin-right` and `margin-left`.  This patch fixes the problem for us, i have replaced scsss.tar.gz on the server, i think it is not used at runtime by primo, but it's used by primo-explore-devenv.

```
diff -r -c orig/src/main/webapp/components/search/searchBar/_search-bar.scss src/main/webapp/components/search/searchBar/_search-bar.scss
*** orig/src/main/webapp/components/search/searchBar/_search-bar.scss	2020-05-19 04:02:19.000000000 +0200
--- src/main/webapp/components/search/searchBar/_search-bar.scss	2020-08-19 07:34:48.000000000 +0200
***************
*** 598,604 ****
            position: absolute;
  
            @include rtl(float, left, right);
!           @include rtl(margin-right margin-left, .25em, 0);
            @include rtl-prop(left, right, -1.5em, auto);
          }
  
--- 598,604 ----
            position: absolute;
  
            @include rtl(float, left, right);
!           @include rtl-prop(margin-right, margin-left, .25em, 0);
            @include rtl-prop(left, right, -1.5em, auto);
          }
```

**Comment by noamamit92** [comment]
Thanks

We actually already noticed and fixed for November (when I merged your pr)
