### ISSUE TITLE
How to inject user information

### ISSUE THREAD

**Issue by danizen** [ExLibrisGroup/primo-explore-devenv#125]
Hi,

Our library would like users to start in a user group without requesting privileges (via Terms of Use), and then once we are certain they've entered their address and phone number, we will change their user group to "PUBLIC" and the TOU will allow requests.

However, we would also like to let them know if they are logged in and in a particular user group, let's call it "PROVISIONAL", we want to give them a message under "Get It".

To do this, I was thinking I would implement a directive prmServiceHeaderAfter and check if the header was "Get It".

What is the best way to access the user information?   AngularJS lets you inject dependencies, right?  Is there a service or something that holds the user information?

**Comment by noamamit92** [comment]
@danizen - I think the better approach will be to use the prm-opac-after hook - that way you know you are in the getit section for sure
from there you should be able to access the jwtUtilService, in a way similar to this:

angular.element(document.querySelector('prm-opac-after')).scope().**$ctrl.locationsService.jwtUtilService**

The bold part is the part that can be accused through the parentCtrl object you should use in you code
