### ISSUE TITLE
Can not establish build environment

### ISSUE THREAD

**Issue by dnwk** [ExLibrisGroup/primo-explore-devenv#127]
Got this error message when I run npm install 

936 verbose node v10.15.3
937 verbose npm  v6.4.1
938 error code ELIFECYCLE
939 error errno 134
940 error canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
940 error Exit status 134
941 error Failed at the canvas@2.8.0 install script.
941 error This is probably not a problem with npm. There is likely additional logging output above.
942 verbose exit [ 134, true ]

**Comment by noamamit92** [comment]
@dnwk  - Did you change your package.json file? Did you add an entry for:

canvas@2.8.0?

**Comment by dnwk** [comment]
Ok. I don't know why that entry was added. I didn't manually add it. But I uninstalled everything and do a clean install. This round it pass.

Thanks
