### ISSUE TITLE
Extend record actions with our custom MARC download service

### ISSUE THREAD

**Issue by danizen** [ExLibrisGroup/primo-explore-devenv#135]
We have added a link to a custom MARC Download Service to our PrimoVE to our Links section on the full record display.  If you browse to https://catalog.nlm.nih.gov/permalink/01NLM_INST/1o1phhn/alma9915909883406676 and then scroll down to links you will see this HTML:

[View and download the MARC Record](https://catalog-utils.nlm.nih.gov/marc/bibs/nlmbib-9915909883406676/)

We now have survey results requesting that we move the MARC Download higher (into the "Record Actions" section).

I am wondering whether there is any way to repurpose a record action we are not using, such as "Excel" to do this, and also whether there is an (unsupported) way to essentially subclass prmActionList and prmActionContainer.

Thanks for any and all suggestions.  We are also considering whether we could simply move up the Links section or something like that.

**Comment by mschwendener** [comment]
> We are also considering whether we could simply move up the Links section or something like that.

There are two ways to do this: 

1)
- Alma -> Discovery -> Configure views -> [pick your view] -> edit [behind the ...] 
-> Full record services -> here you can change the position with the up and down arrows

2) 
If you want to show the links above the 'Send to' actions, you can do so via CSS * 
https://basel.swisscovery.org/permalink/41SLSP_UBS/mmbbsj/alma9971950710105504 

Let me know if you want to know details. 
  

 * https://ideas.exlibrisgroup.com/forums/308176-primo/suggestions/33301972-an-option-to-move-the-send-to-section-in-primo-ve

**Comment by mschwendener** [comment]
>  https://github.com/alliance-pcsg/primo-explore-custom-actions 

Be aware that they are not using Primo VE.

**Comment by danizen** [comment]
This is working out for us so far. Thanks.
