### ISSUE TITLE
Document that custom1.css and custom-js are overwritten

### ISSUE THREAD

**Issue by danmichaelo** [ExLibrisGroup/primo-explore-devenv#15]
Took me some time to understand that `primo-explore/custom/${view}/css/custom1.css` and `primo-explore/custom/${view}/js/custom.js` are overwritten by the `custom-css` and `custom-js` tasks. I think this should be better documented to help people from not accidentally loose work.

Even better would perhaps be if the products (custom1.css and custom.js) could be stored in a different folder, to avoid mixing source files and build products in the same folder?

**Comment by Steve-A-Orr** [comment]
I support this request. Maybe the README files in each folder could spell this out. Luckily, I use Git to track changes and am able to find what is overwritten.

**Comment by Reedyn** [comment]
Indeed, it was very frustrating following instructions (making local changes in `custom1.css`) only to find all work being overwritten.

**Comment by meinbrodt** [comment]
+1

**Comment by noamamit92** [comment]
committed 1d84ffc
