### ISSUE TITLE
The centralCustom module is not loaded

### ISSUE THREAD

**Issue by gpeterso** [ExLibrisGroup/primo-explore-devenv#17]
I'm extracting this as a separate issue from #11. 

It looks like the `customJs` property needs to be defined on the customization object in primoProxy.js in order for the bootstrapping process to find the `centralCustom` module. Otherwise, only the `viewCustom` module gets loaded. 

I will submit a pull request with a fix.

**Comment by noamamit92** [comment]
Thanks, I will review tomorrow

Hope to get some work done this week on the central package
