### ISSUE TITLE
The centralCustom module is no longer loaded in the November release 

### ISSUE THREAD

**Issue by gpeterso** [ExLibrisGroup/primo-explore-devenv#26]
Hi Noam, 

I noticed that the `centralCustom` module in my uploaded CENTRAL_PACKAGE.zip file was no longer loaded after we upgraded to the November release. After setting some breakpoints in app.ts and inspecting the assigned variables on the stack, I determined that this problem is occurring because the `customJs` property does not exist on the `appConfig` global object: 

```
JSON.stringify(appConfig.customization, null, 2);
"{
  "centralCss": "custom/CENTRAL_PACKAGE/css/custom1.css",
  "favIcon": "custom/CENTRAL_PACKAGE/img/favicon.ico",
  "resourceIcons": {},
  "viewJs": "custom/CENTRAL_PACKAGE/js/custom.js",
  "staticHtml": {
    "help": {},
    "homepage": {}
  }
}"
```

Notice that my CENTRAL_PACKAGE custom.js file path is assigned to the `viewJs` property. Prior to the November release, the CENTRAL_PACKAGE custom.js file path was assigned to a `centralJs` property. This is problematic because Primo will only bootstrap the `centralCustom` module if the `appConfig.customization.customJs` is assigned. If only the `appConfig.customization.viewJs` is assigned, then `viewJs` is the only module that gets bootstrapped. Refer to bootstrap_app.ts for more info. 

Is this expected behavior or a bug? Is the `centralCustom` module deprecated? If so, the README should be updated. 

Also, I'll note that this is realated to closed issue #17. 

Jeff

**Comment by gpeterso** [comment]
@noamamit92 Should I submit a bug report via ExL support instead?

**Comment by noamamit92** [comment]
@gpeterso - this was indeed a problem , is fixed in the upcoming February 2017 release
