### ISSUE TITLE
enable debug mode by default

### ISSUE THREAD

**Issue by david-gang** [ExLibrisGroup/primo-explore-devenv#27]
Currently in order to access a the scope we have to write angular.debugWithReloadInfo manually.

I am sure it is possible that the development environment can make it automatically.

Here is the code:
https://github.com/angular/angular.js/blob/master/src/Angular.js#L1816

If we could just inject a small script in the index.html which performs
```javascript
  window.name = 'NG_ENABLE_DEBUG_INFO!' + window.name
```
we essentially make the job.

**Comment by noamamit92** [comment]
I am rejecting this, as other methods seem to be a better alternative
