### ISSUE TITLE
packages installed via npm don't get compiled into custom.js

### ISSUE THREAD

**Issue by thatbudakguy** [ExLibrisGroup/primo-explore-devenv#29]
I followed the instructions [here](https://github.com/noamamit92/primo-explore-altmetrics-widget) to install the example altmetrics widget package. However, the code contained in the package doesn't appear in my package's `custom.js` file.

On [this line](https://github.com/ExLibrisGroup/primo-explore-devenv/blob/master/gulp/tasks/buildCustomJs.js#L34) in the gulp `buildCustomJs` task, it seems like the `customNpmJsModulePath` and `customNpmJsCustomPath` are being ignore with the addition of `'!'+` to the paths. When I remove those, the content is compiled into custom.js normally.

Should the `'!'` be removed, or should I be doing this a different way?

**Comment by gpeterso** [comment]
Huh. So, after you ran `npm install`, which gulp task did you run?

**Comment by thatbudakguy** [comment]
just `gulp run --view=MY_VIEW`, and then played around in the browser to make it refresh. the `buildCustomJs` task gets run, but the contents of the packages' `altmetrics.js` aren't showing up in my `custom.js`.

**Comment by thatbudakguy** [comment]
tried this on a fresh install of the dev environment and couldn't replicate, so I guess it's my `gulpfile` or something. closing.
