### ISSUE TITLE
Create Package Fails

### ISSUE THREAD

**Issue by ealtman52** [ExLibrisGroup/primo-explore-devenv#32]
I am able to edit and preview, but when I try to create package gulp tells me that the gulpfile doesn't contain "create." I see createpackage.js in the tasks folder, and it's referenced in the gulpfile, so I'm not sure what the issue is.

Elizabeth

**Comment by gilax** [comment]
Hi Elizabeth,

I don't know if this is still relevant, but the right command is "create-package" not "create".

Thanks,
Gilad
