### ISSUE TITLE
missing deployment for static help file on localhost

### ISSUE THREAD

**Issue by rochpaul** [ExLibrisGroup/primo-explore-devenv#37]
Hello,

I can't use the custom help file (help_de_DE.html) on localhost. I think it doesn‘t deploy when i run the view with the gulp taskrunner (gulp run --view).

If I create a package and deploy it into back office i can use the static help file. Is there a way to see changes in help file locally?

best regards, Paul

**Comment by uleodolter** [comment]
It seems that help file content is dynamically created on server when /primo-explore/static-file/help?vid=<VIEW>&lang=<LANG>.  Therefore custom/<VIEW>/html/help_*.html need to be deployed on server.  

It would be great if help file creation can be done by primo-explore-devenv,  then real-time edit of help files is much easier without need to deploy on every change.

@noamamit92 @ShoulM can you have a look on this issue ?

**Comment by gilax** [comment]
Is this issue still happening? I couldn't reproduce it

**Comment by uleodolter** [comment]
@gilax It works now for me, local changes are reflected immediatly, it think this issue can be closed.
