### ISSUE TITLE
Cannot access application built with browserify.

### ISSUE THREAD

**Issue by muratseyhan** [ExLibrisGroup/primo-explore-devenv#40]
[After pulling the latest changes](https://github.com/ExLibrisGroup/primo-explore-devenv/tree/e8b528502598a103e923873a6762340a0a0b9645), when I use `gulp run --view <myView> --browserify` to build my package and try to access the application running locally, I get the following message.

    Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.exports._errnoException (util.js:1028:11)
        at exports._exceptionWithHostPort (util.js:1051:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

It works fine when the changes after #30 are discarded.

Kind Regards,
Murat

**Comment by gpeterso** [comment]
Hi Murat, 

I'm seeing this error too. It looks like the problem was first introduced with this commit: 8a5b06db80f96066e8f54009fbdc2f2a75eb10c5

Jeff

**Comment by gpeterso** [comment]
More info... I found that commit 8a5b06db80f96066e8f54009fbdc2f2a75eb10c5 works if I add `--proxy` to the run command (e.g. `gulp run --view CENTRAL_PACKAGE --proxy 'https://primo-server:443' --browserify`).   

Is `--proxy` supposed to be optional or required?

**Comment by gabriele-h** [comment]
I am facing the same issue. The --proxy addition helps insofar, as the application loads at all and the error is gone, but I am facing the eternally wobbling three diamonds.
