### ISSUE TITLE
missing main.js

### ISSUE THREAD

**Issue by BFallert** [ExLibrisGroup/primo-explore-devenv#43]
When  I use `gulp run --view MAN_UB --proxy 'https://primo-49man.hosted.exlibrisgroup.com:443' --browserify` to build my package and try to access the application running locally, I get the following message.

`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '...\Primo_Exlibris\primo-explore\custom\MAN_UB\js\main.js' from '...\Primo_Exlibris\
    at ...\Primo_Exlibris\\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (...\Primo_Exlibris\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (...\Primo_Exlibris\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at ...\Primo_Exlibris\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
`
> (i shorten the path)

When i create in the js directory a empty `main.js` i get no error!

Is a empty `main.js` ok? or need this file some text?

Thanks

**Comment by gpeterso** [comment]
Documentation for the `--browserify` option is pretty much nonexistent at this point. 

Without the `--browserify` option, the build process takes all of the `*.js` files and concatenates them into a `custom.js` file. When using the `--browserify` option, the build process also creates a `custom.js` file, but it only looks at `main.js`, so you need to explicitly import any files / modules using either the `require()` function or the ES2015 `import` statement. Here's an example of the latter:

```javascript
// main.js
// you can also import npm modules here
import './google-analytics.module'
import './blogger-notifications.module'
import PubmedLinkFix from './pubmeb-fix.component'
import HidePcAvailability from './hide-pc-availability.component'

const REQUIRED_MODULES = [ 'googleAnalytics', 
                           'bloggerNotifications' ];

angular
  .module('centralCustom', REQUIRED_MODULES)
  .component('pubmedLinkFix', PubmedLinkFix)
  .component('hidePcAvailability', HidePcAvailability)
  .component('prmServiceLinksAfter', {
    template: '<pubmed-link-fix></pubmed-link-fix>'
  })
  .component('prmFacetAfter', {
    template: '<hide-pc-availability></hide-pc-availability>'
  });
```

Jeff

**Comment by BFallert** [comment]
Thanks Jeff!

i used this option because i read it in https://github.com/ExLibrisGroup/primo-explore-devenv/issues/40
