### ISSUE TITLE
Error: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by omar1015495** [ExLibrisGroup/primo-explore-devenv#44]

**Comment by Reedyn** [comment]
I also have the same issue.

```
Error: getaddrinfo ENOTFOUND il-primo17 il-primo17:1703
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by cwhunt** [comment]
It sounds like you either didn't update PROXY_SERVER on gulp/config.js (documented in README.md) or didn't use the --proxy switch when doing "gulp run --view" (inferred from commit comments and code).
