### ISSUE TITLE
Windows instructions? 

### ISSUE THREAD

**Issue by cbaksik** [ExLibrisGroup/primo-explore-devenv#5]
I downloaded the Windows installer for node.js and am stuck at this line in the instructions: Run the command (from command line) npm install npm@3.3.12 -g.  What dir do I run it from? I tried a few places and it keeps throwing errors.

**Comment by noamamit92** [comment]
In general - the folder you run from is not important.

Can you send us more details? 

1. The node.js version you installed
2. maybe a screen shot of the npm install npm@3.3.12 -g run log

**Comment by cbaksik** [comment]
Thanks for your quick reply. I downloaded the current version, 4.5, using the Windows installer from the main download page because I didn't read closely enough about the versioning. I was able to find a Windows installer for 4.2.6 here: https://nodejs.org/dist/v4.2.6/node-v4.2.6-x64.msi. 

I then opened a command prompt and got this: 

C:\Users\cb>npm install npm@3.3.12 -g
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\cb\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:20:13

    at Object.<anonymous> (C:\Users\cb\AppData\Roaming\npm\node_modules\npm\
bin\npm-cli.js:76:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

C:\Users\cb>

**Comment by david-gang** [comment]
It looks like this is a problem with some cross installation issues of nodejs.
The issues i found where connected to nodejs 5.4
http://stackoverflow.com/questions/34702617/error-cannot-find-module-npmlog-after-npm-update-g
http://jonathanmccormick.me/blog/node-js-troubles-and-a-solution/

In my opinion every LTS version of 4.x should work well, so 4.5 would also have been nice.  (On my machine the development environment also runs with nodejs 6.x.)

I would recommend to uninstall nodejs, restart the machine and install the latest nodejs LTS version which is 4.5 currently.

**Comment by cbaksik** [comment]
I uninstalled 4.2.6 and installed 4.5 LTS version. I still got the error. I did some googling and think I have resolved the issue based on this post: https://github.com/nodejs/node/issues/2814

I had to remove this folder on my Desktop:
C:\Users\corinna\AppData\Roaming\npm\node_modules\npm

and no longer got the error. 

Happily I was able to  move on to the next step, installing gulp. I did get some warnings: 

$ npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

This is Greek to me though.  I tried moving on anyway to the next step, 'npm install' from my GitHub primo-explore-devenv directory, and got these warnings: 

npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a Reg                             Exp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecu                             rity.io/advisories/130
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN prefer global node-gyp@3.4.0 should be installed with -g

(then some successful statements and a tree, then two more warnings)

npm WARN EPACKAGEJSON primo-explore-devenv@1.0.1 No repository field.
npm WARN EPACKAGEJSON primo-explore-devenv@1.0.1 No license field.


I tried moving on to the next steps and got this far: 

corinna@UISWHLPT380900B /cygdrive/c/Users/corinna/Documents/GitHub/primo-explore-devenv
$ gulp run --view HVD_IMAGES
[14:54:57] Using gulpfile ~\Documents\GitHub\primo-explore-devenv\gulpfile.js
[14:54:57] Starting 'connect:primo_explore'...
[14:54:57] Finished 'connect:primo_explore' after 64 ms
[14:54:57] Starting 'watch-js'...
[14:54:57] Finished 'watch-js' after 9.95 ms
[14:54:57] Starting 'setup_watchers'...
[14:54:57] Finished 'setup_watchers' after 2.68 ms
[14:54:57] Starting 'custom-js'...
[14:54:57] Starting 'custom-css'...
[14:54:57] Finished 'custom-js' after 26 ms
[14:54:57] Finished 'custom-css' after 12 ms
[14:54:57] Starting 'run'...
[14:54:57] Finished 'run' after 6.46 μs
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:8003
    External: http://128.103.151.158:8003
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://128.103.151.158:3001
 ----------------------------------------
[BS] Serving files from: primo-explore



Then it hang for over an hour so I killed it. 

I am not sure I configured the gulp config correctly.  I used: 
var PROXY_SERVER = 'http://qa.hollis.harvard.edu:80'

I don't know how to find out what port our hosted app runs on. 

Any suggestions on what to try next? 

Thank you,
Corinna

**Comment by cbaksik** [comment]
I am trying port 443 and it's no longer hanging but I am getting a socket error: 

``$ gulp run --view HVD_IMAGES
[16:48:36] Using gulpfile ~\Documents\GitHub\primo-explore-devenv\gulpfile.js
[16:48:36] Starting 'connect:primo_explore'...
[16:48:37] Finished 'connect:primo_explore' after 968 ms
[16:48:37] Starting 'watch-js'...
[16:48:37] Finished 'watch-js' after 11 ms
[16:48:37] Starting 'setup_watchers'...
[16:48:37] Finished 'setup_watchers' after 3.53 ms
[16:48:37] Starting 'custom-js'...
[16:48:37] Starting 'custom-css'...
[16:48:37] Finished 'custom-js' after 31 ms
[16:48:37] Finished 'custom-css' after 14 ms
[16:48:37] Starting 'run'...
[16:48:37] Finished 'run' after 7.22 μs
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:8003
    External: http://128.103.151.41:8003
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://128.103.151.41:3001
 ---------------------------------------
[BS] Serving files from: primo-explore
Error: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at Socket.socketOnEnd (_http_client.js:305:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
``

**Comment by noamamit92** [comment]
I am investigating this - with no luck so far

I will update if I find the root cause

**Comment by noamamit92** [comment]
Hi,

you should be using the following line:

var PROXY_SERVER = 'https://harvard-primosb.hosted.exlibrisgroup.com:443'

Let me know if it works for you

**Comment by cbaksik** [comment]
Thanks Noam. My environment is now up and running. I had to make some other changes as well and with Allen Jones' help I am all set. I ended up having to make sure that my GitHub repo was NOT in my Windows user profile directory. Putting it at a higher directory level seemed to solve some problems (it's right on my C:\ drive now). Best, Corinna
