### ISSUE TITLE
Open Wiki?

### ISSUE THREAD

**Issue by gpeterso** [ExLibrisGroup/primo-explore-devenv#56]
@noamamit92 It looks like there are a few open issues and PRs requesting documentation improvements. What do you think about [opening up the wiki pages](https://help.github.com/articles/changing-access-permissions-for-wikis/) for this project? That would allow anyone to add/update documentation without having to submit a pull request.

**Comment by noamamit92** [comment]
Hi @gpeterso , I opened the wiki, let's see what happens... :)
