### ISSUE TITLE
Error: getaddrinfo ENOTFOUND your-server your-server:80

### ISSUE THREAD

**Issue by thatbudakguy** [ExLibrisGroup/primo-explore-devenv#6]
1. copied view code in folder `LCC_NEWUI` to `primo-explore/custom/LCC_NEWUI`
2. executed `gulp run --view LCC_NEWUI`
3. browser returns error:
```
Error: getaddrinfo ENOTFOUND your-server your-server:80
   at errnoException (dns.js:28:10)
   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

Does this have anything to do with `config.js` [specifying port 8002](https://github.com/ExLibrisGroup/primo-explore-devenv/blob/master/gulp/config.js#L55), whereas the app appears to be served on port 8003?

Edit: just used `nvm` to make sure I had npm=3.3.12 and node=4.2.6. Still encountering error. I'm on OSX El Cap `10.11.6`.

**Comment by david-gang** [comment]
I think you have to configure the variable [PROXY_SERVER at  config.js](https://github.com/ExLibrisGroup/primo-explore-devenv/blob/master/gulp/config.js#L58-L59)

For example if the url to the UI is 
> http://primo-demo.exlibrisgroup.com:1701/primo-explore/search?vid=Auto1&lang=en_US

Then 
> var PROXY_SERVER = 'http://primo-demo.exlibrisgroup.com:1701';

**Comment by thatbudakguy** [comment]
This was the issue, thanks! Just didn't have it formatted correctly. If any other alliance members happen to see this, I used:
`var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com/';`
