### ISSUE TITLE
Hi Did somebody install Addon or create "Report Broken Links" in Primo? 

### ISSUE THREAD

**Issue by antrez770** [ExLibrisGroup/primo-explore-devenv#63]

**Comment by Reedyn** [comment]
![image](https://user-images.githubusercontent.com/947063/32715473-c9c4720a-c852-11e7-81e5-c1dc13793a76.png)

We have done a local modification that adds "Report Error"-functionality which simply sends some metadata along to a form where the user can submit to our issue management system.

```javascript
// Add report error button
app.controller('FullViewAfterController', [function () {
    var vm = this;
    vm.url = document.location || '';
    var pnx = vm.parentCtrl.item.pnx || false;

    vm.format = pnx.display.type[0] || '';
    if(vm.format === 'article'){
        vm.source = pnx.display.ispartof[0]+' by '+pnx.addata.au[0];
    } else {
        vm.source = 'Published by '+pnx.addata.pub[0]+' and authored by '+pnx.addata.au[0]+' in '+pnx.addata.date[0];
    }
    vm.title = pnx.display.title[0] || '';
    vm.url = document.location || '';
    vm.$onInit = function () {
    }
}]);
app.component('prmFullViewAfter',{
    bindings: {parentCtrl: '<'},
    controller: 'FullViewAfterController',
    template: '<form ng-if="$ctrl.url" id="primo-feedback-form" method="post" action="https://julius.hj.se/forms/libanswers/" target="_blank">\
    <input type="hidden" name="lang" value="en_UK">\
    <input type="hidden" value="Access Issue" name="ticket-type">\
    <input type="submit" id="sfx-feedback" value="Report a problem">\
    <input type="hidden" value="{{$ctrl.title}}" name="ticket-title">\
    <input type="hidden" value="{{$ctrl.source}}" name="ticket-source">\
    <input type="hidden" value="{{$ctrl.url}}" name="ticket-openurl"></form>'});
```

**Comment by antrez770** [comment]
Hi Reedyn, Thank You very much for Your reply, 
I understand it is all the code I need? What is the file I Should insert it in? 
Is it should work with any version of NODE and NPM and Windows (I mean not just last version of node)? 
Thank You.

**Comment by Reedyn** [comment]
@antrez770 This code is added to the custom.js file that is in the custom package for Primo. You might want to add some CSS to make it match your local Primo design as well.

NPM/Node versions is only really relevant to running the Primo development environment, if you can do that already then this will code will work.

**Comment by antrez770** [comment]
Reedyn, thank You I will try and write You. 
also will You meet any Addon for Accessibility Menu for Primo? Or it is not exist?

**Comment by antrez770** [comment]
I see it is working but is looking like a link to another page, I want to do something like PopUp what appears with the form and You can send data from it.

**Comment by Reedyn** [comment]
@antrez770 Popup would be significantly more work, this is just the solution that we have done that works for us.

I don't know of any Accessibility Menu, can you be more specific about what you mean by that?

**Comment by antrez770** [comment]
Yes I know it is more work, I want do this but want see any example. You did the separate page with form right? I Mean Accessibility Menu - Menu what allow to user choice the different options like Grayscale, Big or small text, Contrast and other.

**Comment by antrez770** [comment]
Also how did You do Your solution if You want to place it in Send to line in the Fullpage?

**Comment by Reedyn** [comment]
@antrez770 The separate page is a PHP form that grabs the submitted metadata from POST variables and adds it as hidden input fields that will then be submitted to our issue management system. It's a very local solution that I doubt would work very well at another institution.

I haven't heard of any Accessibility Menu like that. Most patrons I've come in contact with have browser plugins for that kind of solution (many features such as font scaling already exist in all browsers) so they are not dependent on a solution on any particular website.

**Comment by antrez770** [comment]
Do You know how to place Your solution into Send to - section? 
Thank You for answers.

**Comment by Reedyn** [comment]
If you add the code to the `prmActionListAfter` instead of `prmFullViewAfter` it will appear in the "Send to"-section. You would have to style it with CSS accordingly as well.

**Comment by antrez770** [comment]
Thank You Reedyn for all answers. if I will have any more interest question can I ask You?

**Comment by Reedyn** [comment]
I'll do my best to answer if you ask :)

**Comment by antrez770** [comment]
Thank You, and the best way to ask it is here?

**Comment by thatbudakguy** [comment]
@antrez770 you might find these packages useful:
- [primo-explore-report-problem](https://www.npmjs.com/package/primo-explore-report-problem), similar to @Reedyn solution
- [primo-explore-custom-actions](https://www.npmjs.com/package/primo-explore-custom-actions), adds new actions to the "send to" section

So far a good place to talk about primo development is the IGeLU/ELUNA slack workspace, especially the #primodev channel...not sure who is admin but maybe @noamamit92 could invite you?

**Comment by antrez770** [comment]
Yes thank You

**Comment by antrez770** [comment]
Hi thatbudakguy You ask me about invite me to IGeLU/ELUNA slack workspace should I send You the request from slack?

**Comment by antrez770** [comment]
thatbudakguy could You invite me like You want to IGeLU/ELUNA slack workspace, ?
Also is somebody worked with Alma BIB API ?

**Comment by thatbudakguy** [comment]
@antrez770 I used the Bibs and Courses APIs in [primo-explore-course-reserves](https://www.npmjs.com/package/primo-explore-course-reserves), though it was technically on the server side using php, e.g. [here](https://github.com/alliance-pcsg/primo-explore-course-reserves/blob/master/php/getBib.php). There's a bunch of functions in a client-side service that use bib objects [here](https://github.com/alliance-pcsg/primo-explore-course-reserves/blob/master/js/course-reserves.module.js#L261-L390).

I've invited you to the slack so let's take further discussion there and close the issue.

**Comment by antrez770** [comment]
Ok, Thank You, I asked in slack workspace about - "Is somebody knows Accessibility menu plugin for Primo? Or How can I add in right way custom Js files to primo?" But It is look like nobody knows the answer for it.

**Comment by antrez770** [comment]
Hi is somebody can write me the right way add custom JS-code/files to Primo? 
Thank You.

**Comment by gilax** [comment]
Hi @antrez770,
Did you manage adding your custom JS files to Primo?

**Comment by noamamit92** [comment]
closing as it seems to be and outdated conversation
