### ISSUE TITLE
Add BrowserSync on updating CSS/HTML

### ISSUE THREAD

**Issue by jhercher** [ExLibrisGroup/primo-explore-devenv#7]
Hi,

thanks for the useful environment; really saves a lot of work! However, my Browser is only updated on saving the custom.js file. Could you add BrowserSync Updates on saving html or CSS as well?

Thanks in advance

**Comment by noamamit92** [comment]
We will try to do so, but if you want it done immediately and have the knowledge to do so we encourage you to open a pull request.

Thanks

**Comment by danmichaelo** [comment]
Added css support in #13 

I didn't add support for HTML since there's no paths to html files in `config.js`, and the readme in the html folder says "This is how your directory structure should look like", followed by a non-existing image `../../help_files/htmlStructureAug.png`...

**Comment by kelunik** [comment]
Same here, no idea how the naming scheme works except for `home`. I'd be glad if someone could shed some light. https://github.com/ExLibrisGroup/primo-explore-package/issues/1

**Comment by noamamit92** [comment]
I think this can be closed :)
