### ISSUE TITLE
Request: publish latest commits to npm

### ISSUE THREAD

**Issue by ihardy** [ExLibrisGroup/primo-explore-devenv#74]
Hi,

Would you mind publishing the latest commits to npm? In particular I'm looking at the fixes for VE compatibility (https://github.com/ExLibrisGroup/primo-explore-devenv/commit/ee648f8f8b83ed53b2cbc047c3b1d092b12c5c78).

Thanks for considering,

Ian

**Comment by atla5** [comment]
I'll second this as a useful addition/request. 

our current workflow requires that we download the zip file when a new dev gets onboarded. it would be great to be able to run a periodic `npm update -g primo-explore-bu` to keep things up to date.
