### ISSUE TITLE
Disable BrowserSync

### ISSUE THREAD

**Issue by ericgriffis** [ExLibrisGroup/primo-explore-devenv#76]
I'm having trouble testing the devenv with Protractor, and I've read that BrowserSync may have some conflicts with Protractor. I can't find a simple way to disable BrowserSync in the devenv to test if this is the issue, since the application is run by BrowserSync. Is there a simple way to disable BrowserSync, or to run the application without it?

**Comment by gilax** [comment]
hi @ericgriffis, sorry for the late response. did you manage to walk around this issue or you still need a help with it?

**Comment by etgrieco** [comment]
@gilax @ericgriffis is on our team and we have found a workaround on our fork by using webpack instead.
