### ISSUE TITLE
colors.json creates color scheme with links that don't meet color contrast accessibility guidelines

### ISSUE THREAD

**Issue by cbaksik** [ExLibrisGroup/primo-explore-devenv#79]
Using colors.json results in the blue links over grey background with a particular combination of colors that do not have adequate contrast to meet accessibility guidelines

**Comment by lmamak** [comment]
Yes, I've noticed this problem too with the Primo interface. I've reported the color contrast problem to ExLibris.

**Comment by noamamit92** [comment]
This issue will be solved in a Primo release - I am closing this issue, not a problem with the devenv - a problem in Primo itself that is being worked on
