### ISSUE TITLE
Unexpected end of JSON input at Object.parse

### ISSUE THREAD

**Issue by saclaudi** [ExLibrisGroup/primo-explore-devenv#81]
I receive the following message when trying to access primo after running the gulp run command

SyntaxError: Unexpected end of JSON input at Object.parse

I'm using primo ve and the proxy server is configured to point to our production url. No other changes have been made to the files. In the browser I see the primo "loading" graphic but nothing else.

Any help would be appreciated.

Thanks!

**Comment by noamamit92** [comment]
Can you paste in the command line you used to start the server in your
console

In addition can you send the url you configured in config.js and the
content of your view folder

**Comment by barami** [comment]
It made on firefox browser. Chrome does not produce error.
But It failed down silently on chrome. 

![2018-06-12 11-32-43](https://user-images.githubusercontent.com/837438/41267083-ff64cb34-6e34-11e8-9835-28793d6dac7b.png)

When tried chrome, scripts add __bs_notify__ div and remove it.
And scripts add script tag like this

![2018-06-12 11-36-50](https://user-images.githubusercontent.com/837438/41267092-063dc7f8-6e35-11e8-8f83-7c72b194fd4c.png)

i think hilighted line will break and scripts are failed down silently.

**Comment by noamamit92** [comment]
When running the devenv against a ve server you need to run:

>>gulp run —view <vid> —ve

**Comment by dmoore** [comment]
I've run into this problem, too. 

In config.js, I've set the proxy to our VE server:
`var PROXY_SERVER = 'https://sbctc-edcc.primo.exlibrisgroup.com:443';`

Executed gulp with `gulp run --view EDMONDS --ve`

Server starts fine, but the second I resolve `http://localhost:8003/discovery/?vid=EDMONDS` in Chrome or Firefox I get: 

`SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\Users\daniel.moore\Documents\GitHub\edcc-primo\gulp\tasks\servers.js:56:53)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by th5** [comment]
I'm having the issue @dmoore describes above.

Our product Primo VE instance has views such as, vid=01TRI_INST:HC
https://tricolib.primo.exlibrisgroup.com/discovery/search?vid=01TRI_INST:HC&sortby=rank

How should I name my view in gulp to match up?

**Comment by th5** [comment]
Thank you, @dmoore !
