### ISSUE TITLE
Install Timeouts @ [BS] Serving files from: primo-explore

### ISSUE THREAD

**Issue by warrenwatson** [ExLibrisGroup/primo-explore-devenv#9]
Hello, 

My installation process timeouts after the last command line entry:  gulp run --view LOCAL-VIEW

After which the error reads:  [BS] Serving files from: primo-explore

Not sure if this has anything to do with an error generated after "Starting custom-js":

[02:43:14] Starting 'custom-js'...
[02:43:14] 'custom-js' errored after 453 μs
[02:43:14] TypeError: buildParams.customNpmJsModulePath is not a function
    at Gulp.<anonymous> (/Users/WarrenWatson/GitHub/primo-explore-devenv-master/gulp/tasks/buildCustomJs.js:24:151)

Any suggestions?

Thanks

**Comment by thatbudakguy** [comment]
+1 also seeing this. Gulp continues running, but localhost:8003 just says
`Cannot GET /`

**Comment by noamamit92** [comment]
I updated the :
https://github.com/ExLibrisGroup/primo-explore-devenv/blob/master/gulp/config.js

File - if you can update your enviornment and let me know the outcome

Thanks

**Comment by warrenwatson** [comment]
I updated environment with new Config.js file. 
It loaded without error, however, the intall timeouts at the very end while "Serving files from: primo-explore." 

See below.

Suggestions?

+++++++++++++++++++++++++++++

dhcp-10-105-141-55:primo-explore-devenv-master WarrenWatson$ gulp run --view LOCAL_VIEW
[14:07:45] Using gulpfile ~/GitHub/primo-explore-devenv-master/gulpfile.js
[14:07:45] Starting 'connect:primo_explore'...
[14:07:46] Finished 'connect:primo_explore' after 1.05 s
[14:07:46] Starting 'watch-js'...
[14:07:46] Finished 'watch-js' after 46 ms
[14:07:46] Starting 'setup_watchers'...
[14:07:46] Finished 'setup_watchers' after 14 ms
[14:07:46] Starting 'custom-js'...
[14:07:46] Starting 'custom-css'...
[14:07:46] Finished 'custom-js' after 72 ms
[14:07:46] Finished 'custom-css' after 34 ms
[14:07:46] Starting 'run'...
[14:07:46] Finished 'run' after 12 μs
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:8003
    External: http://10.105.141.55:8003
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://10.105.141.55:3001
 --------------------------------------
[BS] Serving files from: primo-explore..........
{TimeOut}

**Comment by noamamit92** [comment]
Thanks, can you attach the PROXY_SERVER definition in your config.js file?

**Comment by warrenwatson** [comment]
I tried a few different definitions last time. This is what it's set to now.

---
var PROXY_SERVER = 'http://localhost:8000';

**Comment by warrenwatson** [comment]
I also tried var PROXY_SERVER = 'http://localhost:3000/' after starting a virtual proxy with Browswersync.

**Comment by noamamit92** [comment]
What is your Primo fe url?

**Comment by warrenwatson** [comment]
I am not entirely sure what you mean by this question. I assume my fe url would be:

http://localhost:8888/primo-explore/search?vid=LOCAL_VIEW
or
http://localhost:3000/primo-explore/search?vid=LOCAL_VIEW  (proxy)

If it didn't time out while serving files from primo-explore.

Should I be using a different fe url?

**Comment by noamamit92** [comment]
The environment is a customization environment for existing ExLibris Primo
customers, by fe url , I mean your library Primo url

**Comment by warrenwatson** [comment]
My institution is an existing ExLibris Primo customer: 
[https://nwu-primosb.hosted.exlibrisgroup.com/primo-explore/search?vid=UNITEDLV&lang=en_US](url)

**Comment by warrenwatson** [comment]
My institution is an existing ExLibris Primo customer:
https://nwu-primosb.hosted.exlibrisgroup.com/primo-explore/search?vid=UNITEDLV&lang=en_US

**Comment by noamamit92** [comment]
So define your PROXY-SERVER in config.js as:


https://nwu-primosb.hosted.exlibrisgroup.com
<https://nwu-primosb.hosted.exlibrisgroup.com/primo-explore/search?vid=UNITEDLV&lang=en_US>
:443

And run :

gulp run --view UNITEDLV

**Comment by warrenwatson** [comment]
This didn't work either...

I set var PROXY_SERVER = 'https://nwu-primosb.hosted.exlibrisgroup.com:443'; 

and performed gulp run --view UNITEDLV

and  everything times out again @ [BS] Serving files from: primo-explore.

**Comment by noamamit92** [comment]
Just to make sure (since I used the same definitiosn and it works for me):

1, in the config.js file there is the following definition:


var PROXY_SERVER = 'https://nwu-primosb.hosted.exlibrisgroup.com:443';


and it appears only once



2. in the browser you opened you typed in the following url:


http://localhost:8003/primo-explore/search?vid=UNITEDLV

**Comment by natazi** [comment]
I updated the config.js with our proxy server, but after the environment is run I see blank screen in the browser.

Proxy server in config.js: 
"var PROXY_SERVER = 'http://primotst.tau.ac.il:1701';"

GULP run:
======
\Primo-NEWUI\devPackageBeta-1.0\primo-explore-devenv\primo-explore> gulp run --view NEWUI_NM
[18:37:38] Working directory changed to ~\Google Drive\Primo-NEWUI\devPackageBeta-1.0\primo-explore-devenv
[18:37:39] Using gulpfile ~\Google Drive\Primo-NEWUI\devPackageBeta-1.0\primo-explore-devenv\gulpfile.js
[18:37:39] Starting 'connect:primo_explore'...
http://primotst.tau.ac.il:1701   11111
[18:37:39] Finished 'connect:primo_explore' after 69 ms
[18:37:39] Starting 'watch-js'...
[18:37:39] Finished 'watch-js' after 7.64 ms
[18:37:39] Starting 'setup_watchers'...
[18:37:39] Finished 'setup_watchers' after 2.51 ms
[18:37:39] Starting 'run'...
[18:37:39] Finished 'run' after 5.6 µs
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:8003
    External: http://132.66.85.178:8003
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://132.66.85.178:3001
 --------------------------------------
[BS] Serving files from: primo-explore
======

URL that I try to see: 
http://localhost:8003/primo-explore/search?vid=NEWUI_NM

That is what I see in cmd when I insert my URL in the browser:
=====
2222 custom/css,custom/html,custom/img,custom/js,custom/NEWUI_NM,custom/template_package
{ viewJs: [],
  viewCss: [],
  centralCss: '',
  favIcon: [],
  libraryLogo: undefined,
  resourceIcons: {},
  homepageHtml: {} }
=====

Any idea what is wrong here?

Thank you.

**Comment by antrez770** [comment]
Hi Did somebody used to install addon for "Report Broken Links" for Primo?
Thanks for all.

**Comment by noamamit92** [comment]
I couldnt connect to :grinning: http://primotst.tau.ac.il:1701/primo-explore/?vid=NEWUI_NM
at all - i am closing this
