### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by spectejb** [ExLibrisGroup/primo-explore-devenv#90]
Can you please identify the license for primo-explore-denenv and create a license file for it?  If you need any recommendations, a permissive license like MIT or BSD would allow the largest number of people to use it. :)

Thank you, in advance, for your help!

**Comment by gilax** [comment]
Hi, I added a BSD 3-Clause license as you request.

Regards,
Gilad

**Comment by spectejb** [comment]
Thank you!
